In [1]:
# pip install numpy

import numpy as np
print(np.__version__)

2.5.1


“NumPy is a Python library used for numerical and scientific computing. It provides a powerful array called NumPy array, which is faster and more efficient than a normal Python list for working with large amounts of numerical data.”

NumPy is a Python library for numerical computing. It provides arrays and mathematical functions that make it easier and more efficient to work with large amounts of numerical data. It is widely used in data science and machine learning.”

What id List:-A list is a built-in Python data structure and is flexible because it can store different types of elements. An array, such as a NumPy array, is mainly designed for numerical data and usually stores elements of the same type. Arrays also support faster and easier mathematical operations, especially for large amounts of data.”

“List is mutable, but string is immutable. If a string is stored inside a list, the list element can be replaced, but the string itself cannot be modified.”

In [2]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
list1=[1,2,3,45]
list2=[32,4,56]
list1+list2

[1, 2, 3, 45, 32, 4, 56]

In [4]:
import numpy as np
arr1=np.array([12,3,4,5.9])
arr2=np.array([9,2,3,4])
arr1+arr2

array([21. ,  5. ,  7. ,  9.9])

In [5]:
import numpy as np
arr1=np.array([2,3,4,"True","False"])
#arr2=np.array([56,"76",32])
print(arr1)

#int+str=str
#bool+int=int
#float+int+float

['2' '3' '4' 'True' 'False']


In [6]:
import numpy as np
arr1=np.array([[10,20,30]])
arr2=np.array([[[2,3,4,5]]])
print(arr1.ndim) # number of dimentaion
print(arr2.ndim)

2
3


In [7]:
import numpy as np
print(np.zeros(15))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#zeros
print(np.zeros((2,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#ones()
print(np.ones(10))
print(np.ones((4,4)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
#Full
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [14]:
#eye()
arr=np.eye(5)
print(arr)
print(arr.ndim)

a2=np.eye(2,4) #can create rectangular matrices
print(a2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [15]:
#identity
idea_arr=np.identity(7) #Only squar matries
print(idea_arr)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [16]:
#diag () is different
import numpy as np
arr = np.diag([1,2,3,7])
print(arr)
print(arr.ndim)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 7]]
2


In [17]:
#diag() is different
#if input is 1D return 2D array

import numpy as np

arr = np.diag([[1,2],
               [3,7]])

print(arr)
print(arr.ndim)

[1 7]
1


In [20]:
#if input is 2D return 1D array
import numpy as np

arr = np.diag([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(arr)
print(arr.ndim)

[1 5 9]
1


In [21]:
arr=np.array(
              [[[1,2],[3,4]],
               [[5,6],[7,8]]]
               )
print(arr.ndim)

d=np.diagonal(arr)
print(d)

3
[[1 7]
 [2 8]]


In [ ]:
# np.eye()       -> always 2D  ## Can create rectangular matrices.
# np.identity()  -> always 2D  ## Only square matrices.

# np.diag()
## If Input is 1D -> Returns 2D Array
## If Input is 2D -> Returns 1D Array

# np.diag() Gives: ValueError: Input must be 1- or 2-d.

# np.diagonal()  -> works with nD arrays #return 1d array

In [22]:
## BASIC ARRAY ATTRIBUTE##

import numpy as np

arr=np.array([1,2,3,4,5,6],ndmin=7) # ndmin: add minimu number of daimention
print(arr)
print(arr.size) # Number of element
print(arr.dtype) # type of array
print(arr.ndim) # number of dimension
print(arr.shape) # size of each dimension
a_flaot = arr.astype(float) # convert interger to str
print(a_flaot)


[[[[[[[1 2 3 4 5 6]]]]]]]
6
int64
7
(1, 1, 1, 1, 1, 1, 6)
[[[[[[[1. 2. 3. 4. 5. 6.]]]]]]]


In [ ]:
#ARRY Indexing- access the particlure element know as indexing
import numpy as np
arr1=np.array([12,3,4,5,6,7])
print(arr1[0])


12


In [ ]:
#working like o and 1 
arr1=np.array([[12,3],[4,5],[6,7]])
print(arr1[2][1]) # 7 
print(arr1[1][0]) # 4

7
4


In [28]:
arr1=np.array([[[1,2,3],[4,5,6]],[[45,67,98],[21,34,65]]])
print(arr1[0,0,0]) # blocks,rows,columns
# if i want 5 indexing 
print(arr1[0,1,1])

1
5


In [29]:
###slicing####

arr1=np.array([12,3,4,5,6,7])
print(arr1[:3]) #start,end,step

[12  3  4]


In [ ]:
###slicing#### 2D array
arr1=np.array([[12,3,4],[5,6,7]])
print(arr1[0][:2])

# find 6
print(arr1[1][1:2])
# find 4
print(arr1[0][2:3])

[12  3]
[6]
[4]


In [37]:
####Slicing### 3D array
arr1=np.array([[[1,2,3, 41],[4,5,6, 71]],[[45,67,98, 100],[21,34,65, 78]]])
print(arr1[:, ::2, ::2])  # blocks, rows, columns

# output [1,2],[45,98]
print(arr1[:, :2, :2 ])

[[[ 1  3]]

 [[45 98]]]
[[[ 1  2]
  [ 4  5]]

 [[45 67]
  [21 34]]]


In [38]:
###np.choose()

choice = [3,0,0] # rows names and index

arr1=np.array([10,20,30,40,67,78])

result=np.choose(choice,arr1) # select values from multiple arrays usning indexing
print(result)

[40 10 10]


In [ ]:
choice = [0,1,1,1]
arr1 = np.array([10,20,30,40])  # zero position
arr2 = np.array([1,2,3,4])      # 1 position

result = np.choose(choice,[arr1,arr2]) 
print(result) # arr1 slect as zero and aar2 select as 1, 

[10  2  3  4]


In [40]:
import numpy as np
choice = [1,7,5,0]
arr0 = [10,20,30,40]
arr1 = [1,2,3,4]
arr2 = [100,200,300,400]
arr3 = [7,8,9,10]
arr4 = [1,2,3,4]
arr5 = [100,200,300,400]
arr6 = [121,122,123,124]
arr7 = [7,8,9,10]

result = np.choose(choice,[arr0,arr1,arr2,arr3,arr4,arr5,arr6,arr7]) 

print(result)

[  1   8 300  40]


In [ ]:
arr1 = np.array([[4,3,2,1],[10,30,40,11]])
arr1[1,-2:-4:-1] # 1 means [10,30,40,11] # Sratrt,end,step

array([40, 30])

In [ ]:
# 1D ARRAy Slicing
arr1 = np.array([4,3,2,1,1,3,4])
arr1[-1:3:-1] # 2 is output

array([4, 3, 1])

In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1[:3])
#print(arr1[2:])#3,4,5

[1 2 3]


In [47]:
#Negative indexing 
arr = np.array([10,20,30,40,50])
print(arr[-3:]) # 30,40,50
print(arr[-2::2]) # 40

[30 40 50]
[40]


In [48]:
##Step slicing

arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[-5:-1:2]) # 5,7

[5 7]


In [57]:
arr = np.array([1,2,3,4,5])
print(arr[:3:1]) # [5,4,3,2,1]

[1 2 3]


In [ ]:
arr = np.array([[1,2,3,4],
               [4,5,6,7],
               [232,34,43,45]])

print(arr[1,1:-3]) # [4,5,6,7] 5 end se b 5 then []

[]


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[-1:1:-2]) # 5,3 start,end(end point not include),steps
print(arr[-2:2:-2]) # 4

[5 3]
[4]


In [64]:
arr3 = np.array([[1,2,3,4],[8,6,7,5],[4,5,6,7]])

#print(arr3[-1:,0::3])
print(arr3[-3:,0::3]) # 8 ,5

[[1 4]
 [8 5]
 [4 7]]


In [66]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [67]:
# access element
print(arr[1,0,2]) #block/row/column

9


In [ ]:
# Row and Column Slicing
# 2D Array Slicing

import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
               ])

#print(arr)

print(arr[1:,::2])  # [4,5,6], output is [4,6] es me [1,] mtlb 2nd row, [1:,] mtlb 2nd row kw bad sb ,[1:3] mtlb 2nd row se 3rd row ke pehle.


[[4 6]
 [7 9]]


In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
               ])
print(arr[-2:]) # es me last -2 row se ke bad [4,5,6][7,8,9] forward jayega isliye
print(arr[:-2]) # revese jayega[1,2,3]


#################IMP########
#arr[-2:]   → second-last से END तक → forward
#arr[:-2]   → START से second-last से पहले तक → forward
#arr[::-1]  → END से START तक → reverse



[[4 5 6]
 [7 8 9]]
[[1 2 3]]


In [ ]:
# Alternate ROW 

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
               ])

print(arr[::2]) # print row alternate

[[1 2 3]
 [7 8 9]]


In [82]:
# Alternate Column

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
               ])

print(arr[1::2, ::]) # print column alternate

[[4 5 6]]


In [ ]:
## Rows and Column Slice

## 2D Array 

In [68]:
# BOOLEAN In dexing (Filtering)

arr1 = np.array([11,2,1,4,5])
print(arr1[arr1%2==0])

[2 4]


In [70]:
##where method

arr1 = np.array([11,2,1,4,5])
result = np.where(arr1>5)
print(result)

(array([0]),)


In [ ]:
## PUT Method
## Replace element at specific indexes

In [83]:
## Flatten()

arr = np.array([[1,2,3,4,5,6]])
print(arr)

## Using Flatten() - return as copy

flat_arr = arr.flatten()  # convert 1D array
print(flat_arr)
flat_arr[1]=1000
print(flat_arr)

reveled_arr = arr.ravel()
reveled_arr[0]=800
print(reveled_arr)
print(arr)

[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
[   1 1000    3    4    5    6]
[800   2   3   4   5   6]
[[800   2   3   4   5   6]]


In [ ]:
####IMP###
#Method        Shape Changes?    Copy/View             Memory Shared?
#---------------------------------------------------------------------
#copy()        No                Copy                  No
#view()        No                View                  Yes
#flatten()     1D                Copy                  No
#ravel()       1D                View (usually)        Yes

In [ ]:
## ARRAY Joining in Numpy using method concatenate

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=np.array([100,200,300,400])
value = np.concatenate((arr1,arr2,arr3))
print(value)

[  1   2   3   4   5   6   7   8 100 200 300 400]


In [86]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [87]:
###Stacking Arrays#####

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
#########VStrack##########--row wise used

a = np.array([[1,2,3],[1,4,5]])
b = np.array([[6,5,4],[2,4,3]])

print(np.vstack((a,b)))


[[1 2 3]
 [1 4 5]
 [6 5 4]
 [2 4 3]]


In [ ]:
#########hStrack##########--column wise used

a = np.array([[1,2,3],[1,4,5]])
b = np.array([[6,5,4],[2,4,3]])

print(np.hstack((a,b)))

[[1 2 3 6 5 4]
 [1 4 5 2 4 3]]


In [91]:
#########dStrack##########

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dstack((a,b)))

[[[1 4]
  [2 5]
  [3 6]]]


In [92]:
# split() method

arr = np.array([100,20,30,67])
print(np.split(arr,2))

[array([100,  20]), array([30, 67])]


In [93]:
# array_Split()

arr = np.array([10000,20000,30000,50000,60000])
np.array_split(arr,4)

[array([10000, 20000]), array([30000]), array([50000]), array([60000])]

In [95]:
## Appending and inserting

## Appending

arr = np.array([1,2,3,4])
arr = np.append(arr,5)

print(arr)


arr1 = np.array([1,2,3,4])
arr1 = np.append(arr1,[5,6])

print(arr1)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [100]:
## Inserting

arr = np.array([1,2,3,4])
print(np.insert(arr,3,20000))



[    1     2     3 20000     4]


In [ ]:
arr1 =

In [106]:
## Deleting Elemenet ##

arr1 = np.array([12,34,54,65,65])
v= np.delete(arr1, 3)
print(v)


[12 34 54 65]


In [107]:
## Change Array Size ###

# resize

arr = np.array([1,2,3,4,5])
new_arr = np.resize(arr,13)

print(new_arr)

[1 2 3 4 5 1 2 3 4 5 1 2 3]


In [111]:
## Sorting array size ##

# Difference
# arr.sort

arr = np.array([4,1,3,2])
sorted_arry = np.sort(arr)

print(sorted_arry)
print(arr)
print(sorted_arry[::-1])

[1 2 3 4]
[4 1 3 2]
[4 3 2 1]


In [112]:
# argsort()

# return the indices that would sort the array

arr = np.array([50,60,40,10])
print(np.argsort(arr))

[3 2 0 1]


In [115]:
## Removed Duplicates ###

#np.unique()

arr=np.array([1,2,2,3,3,4,4,])
print(np.unique(arr))


[1 2 3 4]


In [116]:
## Removed Duplicates ###

#np.Flip()

arr=np.array([1,2,3,4,])
print(np.flip(arr))

[4 3 2 1]
