In [1]:
import numpy as np
print(np.__version__)

2.5.1


In [2]:
## Exercise 1: Create a 1D NumPy array of numbers from 0 to 9

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
## Exercise 2: Convert 1D array to 2D.
arr = np.arange(10)
print(arr)

arr2 = arr.reshape(2,5) # 2 rows and 5 column
print(arr2)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
### Exercise 3: Print Array Attributes
arr = np.array([
                [1,2,3],
                [4,5,6]
                ])

print("Size:-",arr.size)
print("Diamention:-",arr.ndim)
print("Data_type:-",arr.dtype)
print("Shape:-",arr.shape)
print("Array_Size:-",arr.astype)

Size:- 6
Diamention:- 2
Data_type:- int64
Shape:- (2, 3)
Array_Size:- <built-in method astype of numpy.ndarray object at 0x000002D2D33A3F30>


In [15]:
#### Exercise 4: Create a 3×3 NumPy array of all True
arr = np.ones((3,3),dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [20]:
##### Exercise 5: Create a 1D array filled with zeros and another filled with ones

arr = np.zeros(5)
arr2 = np.ones(5)

print(arr)
print(arr2)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
##### Exercise 6: Create a 1D array of 10 evenly spaced values between 5 and 50

arr = np.linspace(5,50,10) # Start,stop,number

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [22]:
##### Exercise 7: Convert a Python list into a NumPy array.

list1 = [10,20,30,40]

arr = np.array(list1)
print(arr)

[10 20 30 40]


In [23]:
##### Exercise 8: Find the memory size of a NumPy array of numbers from 0 to 9.
arr = np.arange(10)
print(arr.nbytes)

80


In [24]:
##### Exercise 9: Reverse a 1D NumPy array

arr = np.array([10,20,30,40,50])

print(arr[::-1])

[50 40 30 20 10]


In [26]:
##### Exercise 10: Create a 3×3 identity matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
##### Exercise 11: Create a 4×4 array and extract its first row and last column

arr = np.arange(1,17).reshape(4,4)
print(arr)
print("First row:-",arr[0,:])  ## arr[row,col]
print("Last column:-",arr[:,-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First row:- [1 2 3 4]
Last column:- [ 4  8 12 16]


In [35]:
#### Exercise 12: Extract Odd Rows and Even Columns

arr = np.arange(1,17).reshape(4,4)
print(arr)

print("ODD Rows and Even col:-",arr[1::2,::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
ODD Rows and Even col:- [[ 5  7]
 [13 15]]


In [ ]:
##### Exercise 13: Stack arrays horizontally - using hstack
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
result = np.hstack((a,b)) ## side by side connect krta he

print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
##### Exercise 14: Slice the first two rows and first two columns from a 4×4 array

arr = np.arange(1, 17).reshape(4, 4)

print(arr)

print("First Two Rows and Two Col:-",arr[:2,:2])

#:2    → 2 = STOP
#::2   → 2 = STEP

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First Two Rows and Two Col:- [[1 2]
 [5 6]]


In [39]:
##### Exercise 15: Replace all odd numbers in a NumPy array with -1.

arr = np.array([1,2,3,4,5,6,7,8,9])

arr[arr%2==1]=-1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#### Exercise 16: Get the indices of non-zero elements in an array
import numpy as np
arr = np.array([0,5,0,8,3,7])
result = np.nonzero(arr)
print(result) # non-zero value ke indexs show krta he


(array([1, 3, 4, 5]),)


In [ ]:
#### Exercise 17: Find the common items between two arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,2,6,9,13])

result = np.intersect1d(arr1,arr2)
print(result) # give a common value

[2 4]


In [45]:
#### Exercise 18: Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([10,20,30])
b = np.array([2,3,5])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[12 23 35]
[ 8 17 25]
[ 20  60 150]
[5.         6.66666667 6.        ]


In [ ]:
#### Exercise 19: Matrix multiplication using Numpy function.
a = np.array([
              [1,2],
              [3,4]
              ])

b = np.array([
              [5,6],
              [7,8]
              ])

result = np.matmul(a,b)
print(result)

#1×5 + 2×7 = 19
#1×6 + 2×8 = 22

#3×5 + 4×7 = 43
#3×6 + 4×8 = 50

[[19 22]
 [43 50]]


In [52]:
#### Exercise 20: Compute the mean, median, and standard deviation of a NumPy array.
arr = np.array([10,20,30,100,200,300])

print("Mean:-",np.mean(arr))
print("Median:-",np.median(arr))
print("Deviation:-",np.std(arr))
print("Maximun:-",np.max(arr))
print("Minimum:-",np.min(arr))

Mean:- 110.0
Median:- 65.0
Deviation:- 107.08252269472673
Maximun:- 300
Minimum:- 10


In [ ]:
### Exercise 21: Remove common items from array
#Given: 

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

result = a[~np.isin(a,b)] # a ki value b me commaon check krega

print(result) # ~ not mtlb hat jayega


[1 2 3 4]


In [ ]:
### Exercise 22: Normalize a NumPy array (values between 0 and 1)
# Use: normalized = (arr - arr.min()) / (arr.max() - arr.min())

arr = np.array([10, 20, 30, 40, 50])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

print(normalized) # small 0, badi value 1 sb bich me


[0.   0.25 0.5  0.75 1.  ]
